name: Check whether the workflow owner can use ARC runners

on:
  workflow_call:
    inputs:
      check_experiments:
        required: false
        type: string
        description: |
          List of experiments for this workfow. If not defined, all default experiments are included.
      triggering_actor:
        required: true
        type: string
        description: The triggering_actor for the workflow. Use github.triggering_actor
      issue_owner:
        required: true
        type: string
        description: The owner of the issue. Use github.event.pull_request.user.login || github.event.issue.user.login
      curr_branch:
        required: true
        type: string
        description: Current branch or tag.
      curr_ref_type:
        required: false
        type: string
        default: branch
        description: The value of "github.ref_type", "branch" or "tag"
      issue_number:
        required: false
        type: string
        default: "5132"
        description: |
          Fetch's GitHub Issue from pytorch/test-infra
          Example: https://github.com/pytorch/test-infra/issues/5132

    outputs:
      label-type:
        description: Type of runners to use
        value: ${{ jobs.runner-determinator.outputs.label-type }}

jobs:
  runner-determinator:
    runs-on: ubuntu-latest
    outputs:
      label-type: ${{ steps.set-condition.outputs.label-type }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_NUMBER: ${{ inputs.issue_number }}
      TRIGGERING_ACTOR: ${{ inputs.triggering_actor }}
      ISSUE_OWNER: ${{ inputs.issue_owner }}
      CHECK_EXPERIMENTS: ${{ inputs.check_experiments }}
    steps:
      - name: Get the workflow type for the current user
        id: set-condition
        run: |
          echo "::set-output name=label-type::"
